name: Label Rebase

on:
  pull_request:
    types: [labeled,unlabeled]

jobs:
  allow:
    if: ${{ github.event.label.name == 'do-not-merge' }}
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Reject
        if: ${{github.event.action == 'labeled'}}
        run: exit 1
      - name: Allow
        if: ${{github.event.action == 'unlabeled'}}
        run: exit 0