name: Label Rebase

on:
  pull_request:
    types: [labeled,unlabeled]

jobs:
  main:
    if: ${{ github.event.label.name == 'do-not-merge' }}
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'